### ISSUE TITLE
Investigate naming of availability sets during rip and replace

### ISSUE THREAD

**Issue by mikedzikowski** [mikedzikowski/AVDRipAndReplace#3]
When using the template spec the rip and replace solution is naming the availability set as "0" - we will need to investigate this and update this to meet customer naming conventions 

![image](https://user-images.githubusercontent.com/34066455/203322565-b99f8f06-bcc9-47ba-a899-84d7bb92cbc9.png)

**Comment by mikedzikowski** [comment]
Ah, I see availability set as a parameter. It is set to false, which is why I wasn't prompted.

**Comment by jamasten** [comment]
Yeah, not everyone uses availability sets so I couldn't make it mandatory.

**Comment by mikedzikowski** [comment]
Resolved - parameter value is set.
